log_dir: logs/loomvideo
dataset_config_path: configs/dataset/train_demo.yaml
deepspeed_config_path: configs/deepspeed_stage2.json
seed: 0
gradient_accumulation_steps: 1
und_loss_weight: 1.0
gen_loss_weight: 1.0
train_steps: 100000
checkpointing_interval: 1000
save_before_train: false
generate_before_train: false
validation_interval: 1000
evaluation_interval: 1000

model:
  trainable_modules:
    gen_model: "all"
  gradient_checkpointing: true
  und:
    pretrained_model_path: checkpoints/Qwen3-VL-8B-Instruct
    only_last_hidden_states: false
    add_source_video: true
  evaluation:
    geneval:
      model_path: checkpoints/evaluation/mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.pth
      model_config_path: libs/mmdetection/configs/mask2former/mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.py
      clip_path: checkpoints/evaluation/ViT-L-14.pt
    gemini:
      api_key: "YOUR_GEMINI_API_KEY"
      base_url: "YOUR_GEMINI_BASE_URL"
      model: "gemini-2.5-pro-06-17"
    openai:
      api_key: "YOUR_OPENAI_API_KEY"
      base_url: "YOUR_OPENAI_BASE_URL"
      model: "gpt-4.1"
  gen:
    pretrained_model_path: checkpoints/Wan2.2-TI2V-5B-Diffusers
    vae:
      scale_factor_spatial: 16
      scale_factor_temporal: 4
    transformer:
      patch_size: [1, 2, 2]
    base_timestep_shift: 1.0
    num_attn_token_base_shift: 64
    timestep_shift_scale: 0.5
    use_source_embedding: true
  # Optional: load weights from a previous training stage
  # pretrained_ckpt_path: path/to/your/checkpoints

data:
  train:
    resolution_buckets: ["640"]
    max_batch_num_attention_tokens: 16384
    estimated_samples_per_batch: 15
    fps: 24
    num_frames: 121
    und_temporal_downsample_factor: 15
    all_dropout_rate: 0.1
    text_dropout_rate: 0.1
    num_workers: 4
  val:
    batch_size: 1

ema:
  use_ema: true
  ema_decay: 0.9999
  ema_start_step: 0
  ema_interval: 1

optimizer:
  learning_rate: 2e-5
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1.0e-8
  adam_weight_decay: 0.0
  max_grad_norm: 1.0

lr_scheduler:
  warmup_steps: 1000

generation:
  negative_prompt: "Oversaturated colors, overexposure, static, blurry details, subtitles, stylized, artwork, painting, still frame, overall gray tone, worst quality, low quality, JPEG artifacts, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn face, deformed, disfigured, malformed limbs, fused fingers, static frame, cluttered background, three legs, crowded background, walking backwards"
  guidance_scale: 5.0
  guidance_scale_edit: 2.5
  guidance_scale_visual: 1.5